### ISSUE TITLE
Can you set up some documentation of how to set these shaders up?

### ISSUE THREAD

**Issue by PSI-Boredom** [marmitoTH/godot-psx-shaders#3]
Im having troubles setting up the shaders. Is it ok if you make either some tutorial(s) in the readme or even make a youtube video?

**Comment by 0xspig** [comment]
Could you be more specific with your issue? Setting them up is the same as any shader. Create a shader material, load the shader, set the parameters. If you're not getting a texture make sure the vertex color isn't black.

**Comment by marmitoTH** [comment]
Yes, it's like any shader in Godot. In your mesh go to Material > New ShaderMaterial > Shader > Load > Select The Shader File, after that you can save the Material and reuse it anywhere.

**Comment by xiiixvv** [comment]
You litteraly just expected me to know all of this as if Im a master of shaders lmao. Could have just put simple instructions on the readme.
